### ISSUE TITLE
转换的有点问题啊

### ISSUE THREAD

**Issue by lxsea20150901** [wdfe/weweb#4]
未转换
![qq 20170817142443](https://user-images.githubusercontent.com/16009864/29398555-d711efae-8357-11e7-8d90-5aaba244a6a5.png)

转换后
![qq 20170817142600](https://user-images.githubusercontent.com/16009864/29398589-07450e86-8358-11e7-9a5e-d2682b558784.png)

**Comment by pgfxm** [comment]
转换时有报错么？这个转出来的效果有点奇怪，方便给个zip包我们试试么？

**Comment by lxsea20150901** [comment]
其他错误没有，就是不能请求网络，然后后来我改了改，可以请求了，但是页面就错乱了。
有QQ没有，我QQ发你

**Comment by pgfxm** [comment]
ok,你加44878623吧
