### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Ivorfason** [wdfe/weweb#6]
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
TypeError: Cannot read property 'findIndex' of undefined
    at /usr/local/lib/node_modules/weweb-cli/bin/weweb:191:30
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by pgfxm** [comment]
你好，这是在什么情况下报的错呢？什么浏览器？
