### ISSUE TITLE
底部tab文字颜色切换问题

### ISSUE THREAD

**Issue by FrankXiong** [wdfe/weweb#7]
只要点击过tab某个按钮，该按钮文字的颜色始终是active状态
浏览器：Chrome 61.0.3163.100
node: v8.1.3
weweb: v0.4.4

![image](https://user-images.githubusercontent.com/8136089/31596038-5e714ae0-b205-11e7-8107-ff5039bf7cd2.png)

**Comment by IOriens** [comment]
Tabbar 的color属性是必填的，现已做兼容，未填相关属性时使用默认色值
![image](https://user-images.githubusercontent.com/8137136/31651286-a9118444-b2e0-11e7-9e79-e78e298df0e1.png)
